from ._resources import split_resources, resolve_contour_levels, bool_resource, merge_resources, NclResources
from ._colors import read_rgb_colormap, get_colormap
from ._style import ncl_style
from ._maps import create_projection, create_map_axes
from ._tickmark import build_grid_locators, apply_gridliner_labels, apply_plain_axis_ticks
from ._contour import ncl_contour_map
from ._panel import ncl_panel_maps
from ._hatching import add_hatching, add_stipple
from ._labelbar import add_labelbar, gsn_labelbar
from ._strings import add_gsn_strings
from ._overlay import (
    overlay_contour,
    overlay_filled_contour,
    overlay_pcolormesh,
    overlay_markers,
    overlay_text,
    overlay_polyline,
    overlay_polygon,
    overlay_rectangle,
    overlay_vectors,
    overlay_quiver,
    add_contour_overlay,
    add_filled_contour_overlay,
    add_marker_overlay,
    add_markers,
    add_text_overlay,
    add_text,
    add_vector_overlay,
    add_vectors,
    add_polyline,
    add_polygon,
    add_rectangle,
)
from ._objects import ScalarField, OverlayLayer, MapPlot, ContourMapPlot, PanelMapPlot
from ._compat import (
    SUPPORTED_RESOURCES,
    list_supported_resources,
    search_supported_resources,
    supported_resources_to_markdown,
    export_resource_compatibility,
    print_supported_resources,
)
from ._workstation import (
    NclWorkstation,
    gsn_open_wks,
    ncl_draw,
    ncl_frame,
    ncl_close,
    draw,
    frame,
)
from ._gsn import (
    gsn_csm_contour_map,
    gsn_csm_contour_map_polar,
    gsn_panel,
    gsn_panel_maps,
)

__all__ = [
    "split_resources",
    "resolve_contour_levels",
    "bool_resource",
    "merge_resources",
    "NclResources",
    "read_rgb_colormap",
    "get_colormap",
    "ncl_style",
    "create_projection",
    "create_map_axes",
    "apply_plain_axis_ticks",
    "apply_gridliner_labels",
    "build_grid_locators",
    "ncl_contour_map",
    "ncl_panel_maps",
    "add_hatching",
    "add_stipple",
    "add_labelbar",
    "gsn_labelbar",
    "add_gsn_strings",
    "overlay_contour",
    "overlay_filled_contour",
    "overlay_pcolormesh",
    "overlay_markers",
    "overlay_text",
    "overlay_polyline",
    "add_rectangle",
    "add_polygon",
    "add_polyline",
    "overlay_rectangle",
    "overlay_polygon",
    "overlay_vectors",
    "overlay_quiver",
    "add_contour_overlay",
    "add_filled_contour_overlay",
    "add_marker_overlay",
    "add_markers",
    "add_text_overlay",
    "add_text",
    "add_vector_overlay",
    "add_vectors",
    "ScalarField",
    "MapPlot",
    "OverlayLayer",
    "ContourMapPlot",
    "PanelMapPlot",
    "SUPPORTED_RESOURCES",
    "list_supported_resources",
    "search_supported_resources",
    "supported_resources_to_markdown",
    "export_resource_compatibility",
    "print_supported_resources",
    "NclWorkstation",
    "gsn_open_wks",
    "ncl_draw",
    "ncl_frame",
    "ncl_close",
    "draw",
    "frame",
    "gsn_csm_contour_map",
    "gsn_csm_contour_map_polar",
    "gsn_panel",
    "gsn_panel_maps",
]
